### ISSUE TITLE
Liberty plugin description missing from the pom.xml 

### ISSUE THREAD

**Issue by vikramkhatri** [IBMStockTrader/stock-quote#1]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.568s
[INFO] Finished at: Mon Apr 02 22:45:59 EDT 2018
[INFO] Final Memory: 10M/134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project stock-quote: Could not resolve dependencies for project com.stocktrader:stock-quote:war:1.0-SNAPSHOT: The following artifacts could not be resolved: net.wasdev.wlp.starters.ms-builder:config:jar:0.1, net.wasdev.wlp.starters.ms-builder:faulttolerance:jar:0.1: Could not find artifact net.wasdev.wlp.starters.ms-builder:config:jar:0.1 in liberty-starter-maven-repo (http://liberty-app-accelerator.wasdev.developer.ibm.com/start/api/v1/repo) -> [Help 1]
[ERROR]

**Comment by jwalcorn** [comment]
Fixed today.
