### ISSUE TITLE
API Connect certificate CN name needs update

### ISSUE THREAD

**Issue by styblope** [IBMStockTrader/stock-quote#6]
Hostnames used within the API Connect service have changed.
https://developer.ibm.com/apiconnect/2018/11/14/hostname-changes-in-api-connect-on-ibm-cloud/

Please update the certificate in `stock-quote/src/main/liberty/config/resources/security/key.jks` and add CN=apiconnect.appdomain.cloud

**Comment by jwalcorn** [comment]
Just delivered an updated key.jks containing this.  See https://github.com/IBMStockTrader/stock-quote/commit/d15fe983390fd0e820a772eed907f7cf6bddb166.  Sorry for the delay.  Of course, re-open if you still have any problems - but this should fix the problem as reported here.
